stages:
- build
- deploy

build:
  stage: build
  when: on_success
  only:
    - dev
    - master
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker login -u directoryx -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY/bangunpos/front-bangun -f dockerfiles/Dockerfile.dev
    - docker push $CI_REGISTRY/bangunpos/front-bangun