stages:
- build
- deploy

build:
  stage: build
  when: on_success
  only:
    - dev
    - master
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker login -u directoryx -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY/bangunpos/front-bangun -f dockerfiles/Dockerfile.dev .
    - docker push $CI_REGISTRY/bangunpos/front-bangun

deploy-dev:
  stage: deploy
  image: junte/ssh-agent
  variables:
    # should be set up at Gitlab CI env vars
    SSH_PRIVATE_KEY: $SSH_DEV_PRIVATE_KEY
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 700 ~/.ssh/id_rsa
    - eval "$(ssh-agent -s)"
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - ssh-keyscan -t rsa 128.199.252.219 > ~/.ssh/known_hosts
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - chmod 644 ~/.ssh/known_hosts
  script:
    # login to gitlab registry       
    - ssh deployer@128.199.252.219 docker login -u directoryx -p $CI_BUILD_TOKEN $CI_REGISTRY
    # then we cd to folder with docker-compose, run docker-compose pull to update images, and run services with `docker-compose up -d`
    - ssh deployer@128.199.252.219 "cd /Web/front-bangun && docker-compose -f docker-compose.yml pull front-bangun && HOME=/home/deployer docker-compose -f docker-compose.yml up -d"
  environment:
      name: dev
  only:
    - dev