stages:
- build
- deploy

build:
  stage: build
  when: on_success
  only:
    - dev
    - master
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker login -u directoryx -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY/bangunpos/front-bangun -f dockerfiles/Dockerfile.dev .
    - docker push $CI_REGISTRY/bangunpos/front-bangun

deploy-dev:
  stage: deploy
  image: junte/ssh-agent
  script:
        # Add the private SSH key to the build environment
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_DEV_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    # login to gitlab registry       
    - ssh deployer@128.199.252.219 docker login -u directoryx -p $CI_BUILD_TOKEN $CI_REGISTRY
    # then we cd to folder with docker-compose, run docker-compose pull to update images, and run services with `docker-compose up -d`
    - ssh deployer@128.199.252.219 "cd /Web/front-bangun && docker-compose -f docker-compose.yml pull front-bangun && HOME=/home/deployer docker-compose -f docker-compose.yml up -d"
  environment:
      name: dev
  only:
    - dev