version: '3'
services:
  vue-ui:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:8080"
    container_name: vue-ui
    volumes:
       - .:/usr/src/app/my-app
       - /usr/src/app/my-app/node_modules
